### ISSUE TITLE
No "Forgot Password" link available

### ISSUE THREAD

**Issue by pealmeid** [microsoft/woodgrove-groceries#1]
I'm evaluating Microsoft Entra and was directed to the Woodgrove sample app.  However, I am not able to sign in using the "e-mail and password" option.

I enter my e-mail and click on the "Next" button and this brings up the password entry option, but there is no "Forgot Password" link as mentioned in the documentation. See screen clip below:

![entra](https://github.com/microsoft/woodgrove-groceries/assets/6384219/7938b57b-a780-48f9-9956-dab6def9602b)

I would like guidance on how to proceed in order to use the "email and password" option, as this is the login method we currently use on our app (currently registered as an Azure B2C app).

Thanks in advance.

**Comment by yoelhor** [comment]
Thanks for the feedback. This issue has been fixed.
