### ISSUE TITLE
TypeScript Version

### ISSUE THREAD

**Issue by mirojs** [microsoft/woodgrove-groceries#17]
Hello, will there be a TypeScript version of this example? Thanks.

**Comment by yoelhor** [comment]
Thanks for your feedback @mirojs . This GitHub repo is used for the live demo https://woodgrovedemo.com . The source code for this web app is C#. We don't plan to add other programing languages samples **for this live demo**. However, can find the Entra external ID code samples in the [code samples](https://learn.microsoft.com/en-us/entra/external-id/customers/samples-ciam-all) document. The [Angular](https://github.com/Azure-Samples/ms-identity-ciam-javascript-tutorial/tree/main/1-Authentication/2-sign-in-angular/SPA) one is TypeScript based.
