### ISSUE TITLE
The Profile button is not working on localhost with Visual Studio 2022

### ISSUE THREAD

**Issue by MihailCC475** [microsoft/woodgrove-groceries#23]
Hi,

We are trying to run Woodgrove Groceries demo on https://localhost:7169/ with Visual Studio 2022 according the instructions provided in the use cases. We managed to make running sign-in and sing-up use cases using self-singed ASP.NET Core HTTPS development local host certificate.

However, 

We did not managed to run User Profile cases on https://localhost:7169/. 
There are no instructions for those cases. 
And when we click the Profile button we receive ODataEerror exception and the app is showing below message
“Can't read the profile due to the following error: Insufficient privileges to complete the operation. Error code: Authorization_RequestDenied”

The same is working on https://woodgrovedemo.com/.

Please can you help with this issue? What/where we should give privileges needed and make User Profile cases running on https://localhost:7169/?

Thank you and Regards,

**Comment by yoelhor** [comment]
The profile page uses Microsoft Graph to read and update the profile. You have to register an application with the corresponding permission to use Graph API
