### ISSUE TITLE
Re-resign in after adding new roles error

### ISSUE THREAD

**Issue by Sipower** [microsoft/woodgrove-groceries#26]
Breakdown:
After adding a new contributor role >select add role>Clicked on prompt to re sign in > directed straight to google sign in page.

Expectation:
Add new role>click on resign in> sent to woodgrove branded sign in page

**Comment by yoelhor** [comment]
It's probably due to the fact that you singed-in with Google. So, the SSO kicks in and takes you directly to Google.
